name: Build/Release Electron App

on:
  push:
    tags:
      - 'v*' # Скрипт спрацює, коли ти створиш тег (наприклад, v1.0.0)

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # GitHub запустить дві паралельні машини: одну з Windows, одну з macOS
        os: [windows-latest, macos-latest]

    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build and Make
        # Ця команда запустить твій forge make
        run: npm run make
        env:
          # Передаємо змінні з GitHub Secrets у процес збірки
          DB_SERVER: ${{ secrets.DB_SERVER }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          # Додай інші змінні, якщо вони потрібні під час збірки

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          # GitHub автоматично знайде файли в папці out/make
          files: |
            out/make/**/*.exe
            out/make/**/*.dmg
            out/make/**/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}